import { CheckboxField, Heading } from "@aws-amplify/ui-react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gh Fresco Web</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div>
        <div>1. Check if repo initialised, if not do</div>
        <div>2. Check if remote is set, if not do</div>
        <div>
          3. Just choose date range to fill fixed number of commits, or select
          each date as below
        </div>
        <div>3-2. When selecting each date, how can I choose number?</div>
        
        <Heading level={6}>Ideas</Heading>

        <div>{`Read with git log --format="%aI" ?`}</div>

        <Heading level={6}>Choose dates to add commit</Heading>
        <div style={{ display: "flex" }}>
          <div>
            <CheckboxField
              size="large"
              label={""}
              name={""}
              value={""}
              // this will select the entire week. interminate means partially checked
              isIndeterminate={true}
            />
            <br />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
          </div>
          <div>
            <CheckboxField size="large" label={""} name={""} value={""} />
            <br />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
          </div>
          <div>
            <CheckboxField size="large" label={""} name={""} value={""} />
            <br />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
            <CheckboxField size="large" label={""} name={""} value={""} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
